live_config_reload = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[env]
TERM = "alacritty"

[font]
size = 13
offset = { x = 1, y = 1 }
normal      = { family = "JetBrainsMono Nerd Font Mono", style = "ExtraLight" }
bold        = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
italic      = { family = "JetBrainsMono Nerd Font Mono", style = "Light Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }

[[keyboard.bindings]]
chars = '\p'
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = '\n'
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
option_as_alt = "Both"
